#!/usr/bin/env bash
DOTFILES=$(pwd)

if [ "$(uname)" == "Darwin" ]; then
  # Set OSX Defaults
  source osx.sh
  # Install Homebrew Packages
  source brew.sh
  source npm.sh
fi

# Install Ruby & Gems
#source gem.sh

# Install Atom Packages
if [ "$1" == "apm" ]; then
  apm install --packages-file=atom/packages.txt
fi
# Install Vagrant Plugins
#vagrant plugin install vagrant-hostsupdater

# Configure git config & ignore
git config --global include.path $DOTFILES/git/.gitconfig
git config --global core.excludesfile $DOTFILES/git/.gitignore

# Run secrets
./secrets

# Setup Symlinks
ln -svf $DOTFILES/.vimrc ~
ln -svf $DOTFILES/.gemrc ~

mkdir -v ~/.atom
ln -vsf $DOTFILES/atom/keymap.cson $DOTFILES/atom/config.cson $DOTFILES/atom/styles.less  ~/.atom

mkdir -pv ~/.config/fish
ln -svf $DOTFILES/fish/aliases.fish $DOTFILES/fish/fishfile $DOTFILES/fish/config.fish $DOTFILES/fish/functions ~/.config/fish
